---
apiVersion: v1
kind: Service
metadata:
  name: litecoin-service
spec:
  selector:
    app: litecoin
  ports:
    - protocol: TCP
      name: rpc
      port: 9332  # Litecoin RPC port
      targetPort: 9332
    - protocol: TCP
      name: p2p
      port: 9333  # Litecoin P2P port
      targetPort: 9333

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: litecoin-pv-volume
  labels:
    type: local
spec:
  storageClassName: local-sc
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/litecoinvol"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/type
          operator: In
          values:
          - node-worker

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: litecoin-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-sc
  resources:
    requests:
      storage: 2Gi

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: litecoin-ingress
spec:
  rules:
    - host: coinlite.detectionserver.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: litecoin-service
                port:
                  number: 9332
